"""Fix project model and schema

Revision ID: 2c9537f61aec
Revises: 5442d2cbb4b7
Create Date: 2024-10-11 15:40:21.380919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import ProgrammingError

# revision identifiers, used by Alembic.
revision: str = '2c9537f61aec'
down_revision: Union[str, None] = '5442d2cbb4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    # Create enum type
    try:
        op.execute('CREATE TYPE projectstatus AS ENUM (\'DRAFT\', \'POSTED\')')
    except ProgrammingError:
        op.execute('ROLLBACK')
        print("ProjectStatus enum type already exists. Skipping creation.")

    # Alter projects table
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('DRAFT', 'POSTED', name='projectstatus'),
               postgresql_using='status::projectstatus',
               comment='Status of the project',
               existing_nullable=True)

    # Alter users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               comment='True if the user is an administrator',
               existing_nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True if the user is an administrator',
               existing_nullable=False)
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'POSTED', name='projectstatus'),
               type_=sa.VARCHAR(),
               comment=None,
               existing_comment='Status of the project',
               existing_nullable=True)

    # Drop the enum type
    op.execute('DROP TYPE IF EXISTS projectstatus')
    # ### end Alembic commands ###