"""Update models

Revision ID: 852c0f1d1e2d
Revises: 91e455100a46
Create Date: 2024-10-03 20:14:07.005685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852c0f1d1e2d'
down_revision: Union[str, None] = '91e455100a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('ctr', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('cpa', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('roas', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('engagement_rate', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('conversions', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.drop_index('ix_users_first_name', table_name='users')
    op.drop_index('ix_users_last_name', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=False)
    op.create_index('ix_users_first_name', 'users', ['first_name'], unique=False)
    op.drop_column('users', 'email')
    op.drop_column('projects', 'conversions')
    op.drop_column('projects', 'engagement_rate')
    op.drop_column('projects', 'roas')
    op.drop_column('projects', 'cpa')
    op.drop_column('projects', 'ctr')
    op.drop_column('projects', 'created_at')
    # ### end Alembic commands ###
